name: DockerHUb CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  docker:
    runs-on: self-hosted
    
    container: docker
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build tests
        uses: docker/build-push-action@v3
        with:
          file: tests.Dockerfile
          tags: devops-training-flask-app-tests:latest
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: prod.Dockerfile
          push: true
          tags: dockerbeikeni/altacucina:latest
  